### PR TITLE
Fix parse error for query_events (fix for PR#360)

### PR DESCRIPTION
**Pull request by dongwook-chan**
related issue: [python-mysql-replication issue#380](https://github.com/julien-duponchelle/python-mysql-replication/issues/380), [pg_cameleon commit#38c7a90
](https://github.com/the4thdoctor/pg_chameleon/commit/38c7a907c36b10053bc0db5232a1cc9ecbfacf83)
Analysis
- Could not parse status variables in query events for MariaDB
- Because the library was not aware of MariaDB-exclusive status variables

Implementation
- Added MariaDB-only status variables
- Added Exception to raise when status variable parse failed
- Added tests for parsing query events for MariaDB

### CODE REVIEW

**Comment by the4thdoctor** [comment]
Any chance to get this PR merged and a new release out? 
I'd like to make a new release for pgchameleon as well :) . 
ta!

**Comment by dongwook-chan** [comment]
@julien-duponchelle 
Just in case you haven't noticed this PR.
I appreciate your effort to keep this project going!

**Comment by julien-duponchelle** [comment]
Thanks I'm trying to get it merge and release during the week end

**Comment by julien-duponchelle** [comment]
Released!

**Pull request merged**
