### PR TITLE
Add XAPrepareEvent, parse last_committed & sequence_number of GtidEvent

### PR DESCRIPTION
**Pull request by etern**
#255

### CODE REVIEW

**Comment by etern** [comment]
Dear maintainers, this PR add XAPrepareEvent, parse last_committed & sequence_number of GtidEvent
- [XAPrepareEvent](https://dev.mysql.com/worklog/task/?id=6860) is generated by XA PREPARE or XA COMMIT ... ONE PHASE. XA protocol is widely used in sharding proxy.
- last_committed and sequence_number is used for [Parallel applier](https://dev.mysql.com/worklog/task/?id=8440), they are required if I want to implement parallel replication myself.

These features only supported in MySQL 5.7, to keep compatible with 5.6, I need to parse mysql version from FormatDescriptionEvent.

Thanks for your review!

**Comment by KunZhou-at** [comment]
Hi @julien-duponchelle, could you take another look for this please? Happy to make updates to this patch as needed.

**Comment by julien-duponchelle** [comment]
Thanks I will merge that and release a version

**Comment by kun-zhou** [comment]
Hi @julien-duponchelle, should this have been merged into main instead of master?

**Comment by julien-duponchelle** [comment]
Oh sorry I did a new release

**Pull request merged**
